development:
  adapter: postgresql
  encoding: unicode
  database: cookpad_dev
  username: doxuanhuy 
  password: 
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cookpad_dev 
  username: doxuanhuy 
  password: 
  host: localhost
  port: 5432
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: cookpad_dev 
  username: doxuanhuy 
  password: 
  host: localhost
  port: 5432
  pool: 5
